export const Div = ({ ...props }) => <div {...props}>{props.children}</div>;
export const Header = ({ ...props }) => <header {...props}>{props.children}</header>;
export const Section = ({ ...props }) => <section {...props}>{props.children}</section>;
export const Footer = ({ ...props }) => <footer {...props}>{props.children}</footer>;
export const Blockquote = ({ ...props }) => <blockquote {...props}>{props.children}</blockquote>;
export const Article = ({ ...props }) => <article {...props}>{props.children}</article>;
export const I = ({ ...props }) => <i {...props}>{props.children}</i>;
export const P = ({ ...props }) => <p {...props}>{props.children}</p>;
export const B = ({ ...props }) => <b {...props}>{props.children}</b>;
export const Q = ({ ...props }) => <q {...props}>{props.children}</q>;
export const S = ({ ...props }) => <s {...props}>{props.children}</s>;
export const Label = ({ ...props }) => <label {...props}>{props.children}</label>;
export const Span = ({ ...props }) => <span {...props}>{props.children}</span>;
export const H1 = ({ ...props }) => <h1 {...props}>{props.children}</h1>;
export const H2 = ({ ...props }) => <h2 {...props}>{props.children}</h2>;
export const H3 = ({ ...props }) => <h3 {...props}>{props.children}</h3>;
export const H4 = ({ ...props }) => <h4 {...props}>{props.children}</h4>;
export const H5 = ({ ...props }) => <h5 {...props}>{props.children}</h5>;
export const H6 = ({ ...props }) => <h6 {...props}>{props.children}</h6>;
export const UL = ({ ...props }) => <ul {...props}>{props.children}</ul>;
export const OL = ({ ...props }) => <ol {...props}>{props.children}</ol>;
export const LI = ({ ...props }) => <li {...props}>{props.children}</li>;
export const A = ({ ...props }) => <a {...props} href={props.href}>{props.children}</a>;
export const Img = ({ ...props }) => <img {...props} src={props.src} alt={props.alt} />;
export const Form = ({ ...props }) => <form {...props}>{props.children}</form>;
export const Input = ({ ...props }) => <input {...props} type={props.type} name={props.name} value={props.value || props.children} />;
export const TextArea = ({ ...props }) => <textarea {...props} name={props.name}>{props.children}</textarea>;
export const Button = ({ ...props }) => <button {...props} name={props.name}>{props.children}</button>;
export const Svg = ({ ...props }) => <svg {...props}>{props.children}</svg>;
export const Path = ({ ...props }) => <path {...props} />;
export const Nav = ({ ...props }) => <nav {...props}>{props.children}</nav>;
export const Main = ({ ...props }) => <main {...props}>{props.children}</main>;
export const Aside = ({ ...props }) => <aside {...props}>{props.children}</aside>;
export const Figure = ({ ...props }) => <figure {...props}>{props.children}</figure>;
export const FigCaption = ({ ...props }) => <figcaption {...props}>{props.children}</figcaption>;
export const Time = ({ ...props }) => <time {...props}>{props.children}</time>;
export const Mark = ({ ...props }) => <mark {...props}>{props.children}</mark>;
export const Code = ({ ...props }) => <code {...props}>{props.children}</code>;
export const Pre = ({ ...props }) => <pre {...props}>{props.children}</pre>;
export const Small = ({ ...props }) => <small {...props}>{props.children}</small>;
export const Sup = ({ ...props }) => <sup {...props}>{props.children}</sup>;
export const Sub = ({ ...props }) => <sub {...props}>{props.children}</sub>;
export const Strong = ({ ...props }) => <strong {...props}>{props.children}</strong>;
export const Em = ({ ...props }) => <em {...props}>{props.children}</em>;
export const Address = ({ ...props }) => <address {...props}>{props.children}</address>;
export const Dd = ({ ...props }) => <dd {...props}>{props.children}</dd>;
export const Dl = ({ ...props }) => <dl {...props}>{props.children}</dl>;
export const Dt = ({ ...props }) => <dt {...props}>{props.children}</dt>;
export const Table = ({ ...props }) => <table {...props}>{props.children}</table>;
export const THead = ({ ...props }) => <thead {...props}>{props.children}</thead>;
export const TBody = ({ ...props }) => <tbody {...props}>{props.children}</tbody>;
export const Tr = ({ ...props }) => <tr {...props}>{props.children}</tr>;
export const Td = ({ ...props }) => <td {...props}>{props.children}</td>;
export const Th = ({ ...props }) => <th {...props}>{props.children}</th>;
export const Select = ({ ...props }) => <select {...props}>{props.children}</select>;
export const Option = ({ ...props }) => <option {...props}>{props.children}</option>;
export const Caption = ({ ...props }) => <caption {...props}>{props.children}</caption>;
