import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import ServProviders from '@/components/server/ServProviders';
import type { WithChildrenType } from './types';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: WithChildrenType) {
  return (
    <html lang="en">
      <body>
          <ServProviders>{children}</ServProviders>
      </body>
    </html>
  );
}
